### ISSUE TITLE
Bugs After Update

### ISSUE THREAD

**Issue by py7hon** [VIPAPP-team/appmark#2]
![](https://share.dmca.gripe/ujPC86fJUgJrCYeE.png)
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.vipapp.appmark2.project.AndroidManifest.getPackage()' on a null object reference
	at com.vipapp.appmark2.project.Project.getPackage(Unknown Source)
	at com.vipapp.appmark2.project.AIF.add_default_project_settings(Unknown Source)
	at com.vipapp.appmark2.project.AIF.update_aif(Unknown Source)
	at com.vipapp.appmark2.project.AIF.load(Unknown Source)
	at com.vipapp.appmark2.utils.CallableThreadLoader.lambda$reload$0$CallableThreadLoader(Unknown Source)
	at com.vipapp.appmark2.utils.-$$Lambda$CallableThreadLoader$mhBTinzjYtN3Jpna9vwOC6M_FoE.run(lambda)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by y9san9** [comment]
if you are trying to import project from other app, then you will get crash because of incorrect .aif file settings
(it is trying to get AndroidManifest file from path that doesn't exist)
If you got this crash with appmark project then write and I'll check this problem

**Comment by y9san9** [comment]
Ok, I have fixed this issue even if you are importing project
